
export enum EOperationDB {
  TRANSACTION = 'TRANSACTION',
  READ = 'READ',
  UPSERT = 'UPSERT',
  DELETE = 'DELETE',
  SYSTEMLOGS = 'SYSTEMLOGS',
  INDEXES = 'INDEXES',
  DELETECOLLECTION = 'DELETECOLLECTION',
  RENAMECOLLECTION = 'RENAMECOLLECTION',
  LISTCOLLECTIONS = 'LISTCOLLECTIONS',
  SETUPCOLLECTIONSCHEME = 'SETUPCOLLECTIONSCHEME',
  BACKUP = 'BACKUP',
  LISTDATABASES = "LISTDATABASES",
  DELETEDATABASE = "DELETEDATABASE",
  RELEASEINFO = "RELEASEINFO"
}
